apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  labels:
    app: server-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-pod
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: server-pod
      labels:
        app: server-pod
    spec:
      containers:
      - image: gomzalo/server-g3:v4
        name: server-container
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server-service
spec:
  # type: LoadBalancer
  selector:
    app: server-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-pod
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: front-pod
      labels:
        app: front-pod
    spec:
      containers:
      - image: gomzalo/front-g3:latest
        name: front-container
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: LoadBalancer
  selector:
    app: front-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
